### PR TITLE
Ensure MapReduceTask uses the db returned by the application router(s)

### PR DESCRIPTION
**Pull request by sleepyjames**
This PR changes to the default db to be the one returned by the applications router.

### CODE REVIEW

**Comment by Kazade** [comment]
Rather than using `model.objects.all().db`, this should instead use `django.db.router.db_for_read(model)` then I'll happily merge this :)

**Comment by sleepyjames** [comment]
Done, however I'm sure this will be superseded by all the work in https://github.com/potatolondon/djangae/pull/536 perhaps ?

**Comment by Kazade** [comment]
@sleepyjames No that's an additional thing, we still need to support the mappers app even if we deprecate it. One of the tests is now failing :(

**Comment by sleepyjames** [comment]
Ok fixed properly this time. Didn't run the uniquetool tests :-|

**Pull request merged**
