### PR TITLE
Pipelines & MapReduce

### PR DESCRIPTION
**Pull request by chargrizzle**
Adds native pipeline and mapreduce support! 

This will deprecate djangae.contrib.mappers

### CODE REVIEW

**Comment by chargrizzle** [comment]
We will need to reimplement uniquetool for all the tests to pass

**Comment by chargrizzle** [comment]
Uniquetool has been reimplemented

**Comment by seawolf42** [comment]
Realistically, how close is this to being pulled? If I want to start writing MapReduce tasks on djangae, should I be working with the existing djangae.contrib.mappers code or should I anticipate a not-too-far-off implementation of this?

**Comment by Kazade** [comment]
This PR is waiting for review - it's a pretty big change and I can't promise when I'll find time for it. The existing Mapreduce code will stay around under contrib for the foreseeable future and even when it's removed it will be maintained on the potatolondon GitHub.  

Sorry for the delay on this!

**Comment by seawolf42** [comment]
The existing MR code only performs map, though, right? So if I want full mapreduce I need something new. I haven't actually used this patch but I understand it's the full pipeline, is that true?

Documentation for and around mapreduce is very lacking (especially examples). Is there anything I can do to help out with this? I'm happy to be a guinea pig and also build some examples and shore up the documentation, but I'll need a quick hand getting my first job running and insight into which way is the expected way moving forward. I'm in need of full MR sooner rather than later, so if there is anything I can do to help with testing, documenting, or developing I am happy to put in the time.

**Comment by chargrizzle** [comment]
That is correct, the existing mappers only supports map, we are working on a deprecation process to support both versions. This PR means you will be able to use the full appengine MapReduce api as well as the pipelines stuff. It also includes an input splitter for the Django ORM.

**Comment by seawolf42** [comment]
OK, excellent. Please let me know (here or in private message) how I can personally assist this effort, I have a legitimate business use case for it and can devote time to making it work with a little help to bootstrap my understanding.

**Comment by seawolf42** [comment]
I've gotten this working in development, but I am getting HTTP 400 errors in production when I try to run a job. There are no associated log entries with the errors. Any guidance on how to begin troubleshooting this?

**Comment by adamalton** [comment]
400 status errors in production are usually caused by not having your
custom domain name in ALLOWED_HOSTS.  But if it's only when running
mapreduce jobs then... maybe you're specifying the 'target' and <target>.
your-app.appspot.com is not in ALLOWED_HOSTS?

Adam

**Comment by seawolf42** [comment]
No target is being explicitly specified (is the default the project name or does it mangle it somehow?), and all app-level variants of the appspot.com URL as well as the custom domain are in ALLOWED_HOSTS. I do not have any modules other than the default, so no module variants are specified in ALLOWED_HOSTS, though... is that a problem?

jeff

**Comment by adamalton** [comment]
Maybe it's not that then.

And without seeing a traceback or logging or code setup I'm probably going
to struggle to give any useful suggestions!  If Django isn't logging the
exception, maybe you can create a middleware which will?

Adam

**Comment by seawolf42** [comment]
Fair enough. I'd be happy to make a middleware but I'm not quite sure how to go about doing that in this case. Suggestions for what would be most helpful?

Here's everything I can get out of Google's Console log at the moment:

05:20:04.130 POST 400 51 B 13 ms AppEngine-Google; (+http://code.google.com/appengine) /mapreduce/kickoffjob_callback/15721583146899A014779
0.1.0.2 - - [28/Mar/2016:05:20:04 -1000] "POST /mapreduce/kickoffjob_callback/15721583146899A014779 HTTP/1.1" 400 51 https://<domain>/mapreduce/command/start_job "AppEngine-Google; (+http://code.google.com/appengine)" "<version>.<project>.appspot.com" ms=13 cpu_ms=22 cpm_usd=5.699e-9 instance=00c61b117c340652e794d7c72810c0a34e9963df app_engine_release=1.9.35 trace_id=b9a09e689569dcb37823164bf8180903
{
    metadata: {
        projectId: "134818411256"
        serviceName: "appengine.googleapis.com"
        zone: "us3"
        labels: {
            appengine.googleapis.com/request_id: "56f94ba400ff01fd53bc36bc2a0001737e646973747261637465642d676f6f73650001312d3135000100"
            appengine.googleapis.com/module_id: "default"
            appengine.googleapis.com/version_id: "1-15"
            appengine.googleapis.com/clone_id: "00c61b117c340652e794d7c72810c0a34e9963df"
        }
        timestamp: "2016-03-28T15:20:04.130387Z"
        projectNumber: "134818411256"
    }
    protoPayload: {
        @type: "type.googleapis.com/google.appengine.logging.v1.RequestLog"
        appId: "s~<project>"
        versionId: "1-15"
        requestId: "56f94ba400ff01fd53bc36bc2a0001737e646973747261637465642d676f6f73650001312d3135000100"
        ip: "0.1.0.2"
        startTime: "2016-03-28T15:20:04.130387Z"
        endTime: "2016-03-28T15:20:04.143920Z"
        latency: "0.013533s"
        megaCycles: "22"
        method: "POST"
        resource: "/mapreduce/kickoffjob_callback/15721583146899A014779"
        httpVersion: "HTTP/1.1"
        status: 400
        responseSize: "51"
        referrer: "https://<domain>/mapreduce/command/start_job"
        userAgent: "AppEngine-Google; (+http://code.google.com/appengine)"
        urlMapEntry: "wsgi.application"
        host: "<version>.<project>.appspot.com"
        cost: 5.699e-9
        taskQueueName: "default"
        taskName: "2614320489081472311"
        instanceIndex: -1
        instanceId: "00c61b117c340652e794d7c72810c0a34e9963df"
        appEngineRelease: "1.9.35"
        traceId: "b9a09e689569dcb37823164bf8180903"
    }
    insertId: "2016-03-28|08:20:09.145054-07|10.106.154.136|-1878687934"
    log: "appengine.googleapis.com/request_log"
    httpRequest: {
        status: 400
    }
    operation: {
        id: "56f94ba400ff01fd53bc36bc2a0001737e646973747261637465642d676f6f73650001312d3135000100"
        producer: "appengine.googleapis.com/request_id"
    }
}

**Comment by chargrizzle** [comment]
Hi @seawolf42, I've been out of the country for a few weeks but I'm back now. First thing to see is  whether or not you can confirm this is hitting djangae, the first thing that sticks out to me is there is no trailing slash on the POST request, this could be caused by a redirect

**Comment by seawolf42** [comment]
Welcome back!

What's interesting to me is that it works correctly in development, but not in production. When I run it locally I get the following log output:

INFO     2016-03-28 07:10:02,215 runserver.py:292] default: "POST /mapreduce/command/start_job HTTP/1.1" 200 41
INFO     2016-03-28 07:10:02,234 handlers.py:1381] Processing kickoff for job 1572068418180AB3B2CDF
INFO     2016-03-28 07:10:02,240 runserver.py:292] default: "GET /mapreduce/command/list_jobs?cursor= HTTP/1.1" 200 12
INFO     2016-03-28 07:10:02,386 runserver.py:292] default: "POST /mapreduce/kickoffjob_callback/1572068418180AB3B2CDF HTTP/1.1" 200 -
INFO     2016-03-28 07:10:02,504 models.py:31] on_link_changed(): 4504149383184384
INFO     2016-03-28 07:10:02,600 models.py:31] on_link_changed(): 4572868859920384
<truncated>
INFO     2016-03-28 07:10:03,141 runserver.py:292] default: "POST /mapreduce/worker_callback/1572068418180AB3B2CDF-0 HTTP/1.1" 200 -
INFO     2016-03-28 07:10:03,252 models.py:31] on_link_changed(): 4785624359895040
<truncated>
INFO     2016-03-28 07:10:06,442 runserver.py:292] default: "POST /mapreduce/worker_callback/1572068418180AB3B2CDF-7 HTTP/1.1" 200 -
INFO     2016-03-28 07:10:06,514 runserver.py:292] default: "POST /mapreduce/controller_callback/1572068418180AB3B2CDF HTTP/1.1" 200 -
INFO     2016-03-28 07:10:08,564 runserver.py:292] default: "POST /mapreduce/controller_callback/1572068418180AB3B2CDF HTTP/1.1" 200 -
INFO     2016-03-28 07:10:10,653 runserver.py:292] default: "POST /mapreduce/controller_callback/1572068418180AB3B2CDF HTTP/1.1" 200 -
INFO     2016-03-28 07:10:12,710 runserver.py:292] default: "POST /mapreduce/controller_callback/1572068418180AB3B2CDF HTTP/1.1" 200 -
INFO     2016-03-28 07:10:14,767 runserver.py:292] default: "POST /mapreduce/controller_callback/1572068418180AB3B2CDF HTTP/1.1" 200 -
INFO     2016-03-28 07:10:16,814 runserver.py:292] default: "POST /mapreduce/controller_callback/1572068418180AB3B2CDF HTTP/1.1" 200 -
INFO     2016-03-28 07:10:17,178 runserver.py:292] default: "POST /mapreduce/worker_callback/1572068418180AB3B2CDF-0 HTTP/1.1" 200 -
INFO     2016-03-28 07:10:17,571 runserver.py:292] default: "POST /mapreduce/worker_callback/1572068418180AB3B2CDF-1 HTTP/1.1" 200 -
INFO     2016-03-28 07:10:18,035 runserver.py:292] default: "POST /mapreduce/worker_callback/1572068418180AB3B2CDF-2 HTTP/1.1" 200 -
INFO     2016-03-28 07:10:18,361 runserver.py:292] default: "POST /mapreduce/worker_callback/1572068418180AB3B2CDF-3 HTTP/1.1" 200 -
INFO     2016-03-28 07:10:18,875 runserver.py:292] default: "POST /mapreduce/controller_callback/1572068418180AB3B2CDF HTTP/1.1" 200 -
INFO     2016-03-28 07:10:19,046 runserver.py:292] default: "POST /mapreduce/worker_callback/1572068418180AB3B2CDF-4 HTTP/1.1" 200 -
INFO     2016-03-28 07:10:19,661 runserver.py:292] default: "POST /mapreduce/worker_callback/1572068418180AB3B2CDF-5 HTTP/1.1" 200 -
INFO     2016-03-28 07:10:20,064 runserver.py:292] default: "POST /mapreduce/worker_callback/1572068418180AB3B2CDF-6 HTTP/1.1" 200 -
INFO     2016-03-28 07:10:20,480 runserver.py:292] default: "POST /mapreduce/worker_callback/1572068418180AB3B2CDF-7 HTTP/1.1" 200 -
INFO     2016-03-28 07:10:20,926 handlers.py:1278] Final result for job '1572068418180AB3B2CDF' is 'success'
INFO     2016-03-28 07:10:20,932 runserver.py:292] default: "POST /mapreduce/controller_callback/1572068418180AB3B2CDF HTTP/1.1" 200 -
INFO     2016-03-28 07:10:21,029 runserver.py:292] default: "POST /mapreduce/finalizejob_callback/1572068418180AB3B2CDF HTTP/1.1" 200 -

So it looks like the trailing slash is not here either, but it completes without redirects or other issues.

Want to take this to email and I can post a summary here once we figure it out?

**Comment by chargrizzle** [comment]
Sure, where can I contact you?

**Comment by seawolf42** [comment]
jeff@jke.net

**Comment by Kazade** [comment]
@chargrizzle OK here are my first batch of comments :)

- I think we should combine mapreduce and pipelines under a single contrib app, but I don't know what that should be called yet...
- In uniquetool, just replace CleanMapper with NewCleanMapper etc. No-one is likely importing and using these outside of the uniquetool app themselves so we can just swap out the implementation
- MapreducePipeline should be able to take actual functions and input reader classes and not just dotted paths to them. Maybe that's the case anyway but the tests don't seem to imply that. 
- As contrib.mappers will be deprecated by this merge, I suggest that we should put a warnings.warning thing in there to alert people
- Also we should probably move defer_iteration from mappers into this new app, whatever it should be called, and as defer_iteration doesn't use mapreduce we should use a more generic app name like "iteration" or "tasks" or something. Again, suggestions welcome!

Let me know if you have any thoughts about the naming of this new parent app!

**Comment by Kazade** [comment]
Oh, @chargrizzle one other thing. We should probably provide QuerysetPipeline as a subclass to MapreducePipeline which passes up the input reader etc. to iterate the queryset. Ideally it would only require the queryset as a param.

**Comment by Kazade** [comment]
OK, I'm working on this. As it stands this isn't really the approach we're after - ideally we want a nice API which hides the nasty details of mapreduce + pipelines, integrates well with Django querysets and caters for the most common use-cases. I'll update this PR when I've worked out what that should look like.

**Comment by seawolf42** [comment]
Any progress on this? I have a large vested interest in seeing it finalized. I am currently still unable to run in production and don't understand what exactly the problem is, but if it's still in flux then I might be better off waiting?

**Comment by Kazade** [comment]
OK things have just diverged too much for me to (safely) resolve the conflicts. So, my plan is as follows:

1. I've created a branch called "processing-module" which has `djangae.contrib.processing` copied from the chargrizzle-pipelines branch
2. I intend to change `djangae.contrib.mappers` to be implemented in terms of  `djangae.contrib.processing.mapreduce` - i.e. retain the existing API, but just as a layer on top of the new processing module. This resolves the urls.py conundrum (e.g. which app handles _ah/mapreduce?). Mappers will no longer be a Django app, it will just contain the old (deprecated) API. This provides an easy stepping stone to the new app without breaking old code (aside from changing INSTALLED_APPS and urls.py includes).
3. I'll add more documentation and tests
4. Once merged I'll make a ticket to implement `uniquetool` in terms of `processing` so we can in future remove `mappers` (and move it to a separate Git repo on the potato Github)

**Pull request closed without merging**
