### PR TITLE
Add `djangae.compat`

### LINKED ISSUE #964: Breaking change (from SDK), sandbox moved in 1.9.60
Having updated the SDK to the latest build, alot of classes have moved inside a `runtime` package, to resolve the issue I have replaced `google.appengine.tools.devappserver2.python`  with `google.appengine.tools.devappserver2.python.runtime` in all of the Djangae imports

### PR DESCRIPTION
**Pull request by igniteflow**
Fixes #964

Summary of changes proposed in this Pull Request:
- Add `djangae.compat` as a central place to handle module/package changes in SDK versions 
- Supporting caching of downloaded SDK versions

PR checklist:
- [x] Updated relevant documentation
- [x] Updated CHANGELOG.md 
- [ ] Added tests for my change

### CODE REVIEW

**Comment by Kazade** [comment]
@igniteflow could you split this into two PRs? The compat one is an insta-merge, but I need time to think about the caching thing

**Comment by igniteflow** [comment]
@Kazade yes, will do that now

**Comment by adamalton** [comment]
Woo!

**Comment by farridav** [comment]
Nice work @igniteflow, exactly what I was thinking (but didn't have time to PR it) 👍

**Pull request merged**
