### PR TITLE
Feature/flake8

### LINKED ISSUE #985: Create .flake8 file to catch line-length issues
Issue description

Add a .flake8 file that silences all known issues in the code except for line length, and sets the max line length to 100 characters. This is not enforced in any way (open to discussion but there are currently too many long lines to start enforcing yet) but editors that incorporate flake8 into their visual feedback will inform the user of lines that are too long in files they are editing. Partial address of #982.

Steps to reproduce

    $ flake8 djangae

Traceback or other info

* Djangae version: all
* Django version: all
* App Engine SDK version: all
* Using Cloud SDK: N/A

### PR DESCRIPTION
**Pull request by seawolf42**
Fixes #985.

Summary of changes proposed in this Pull Request:
- Add .flake8 file to move towards enforcement code standard

PR checklist:
- [N/A] Updated relevant documentation
- [x] Updated CHANGELOG.md 
- [N/A] Added tests for my change

### CODE REVIEW

**Comment by adamalton** [comment]
I think that when @Kazade said:

> I'm happy to accept a PR that adds a .flake8 which is PEP8 but warns for >100 chars

what he meant was: it should warn for everything, but the line length should be 100 chars, rather than the usual 80.

**Comment by seawolf42** [comment]
Happy to make that change, but would like to hear confirmation from @Kazade first. Just let me know.

**Comment by Kazade** [comment]
Yeah sorry I wasn't clear in my wording. We want to see the errors so we can fix them incrementally :)

**Comment by seawolf42** [comment]
OK, just updated the `.flake8` to report everything. Thanks for the clarification!

**Pull request merged**
