### PR TITLE
Wsgi wrapper fix

### PR DESCRIPTION
**Pull request by jacobg**

### CODE REVIEW

**Comment by Kazade** [comment]
Same again, merging this is going to remove stuff from master

**Comment by olasitarska** [comment]
@jacobg could you submit a new pull request that only applies WSGI wrapper changes, without removing BinaryField?

Thanks!

**Comment by olasitarska** [comment]
Actually, I could just cherry pick a7e59ab. @Kazade are you happy for this a7e59ab to be merged?

**Comment by moggers87** [comment]
Looks like this was pulled in with https://github.com/potatolondon/djangae/pull/531

**Comment by olasitarska** [comment]
Yup, looks like this change is in master now :)

**Pull request closed without merging**
