### PR TITLE
Replace print with logging

### LINKED ISSUE #976: Silence output during `manage.py test` execution
Unit tests and other functions are using print statements for output. This should be changed by:
* turning all `print()` calls in unit tests to `logging.XXX()` calls
* silencing all `print()` statements in command and other output when `test` is in `sys.argv`

### PR DESCRIPTION
**Pull request by seawolf42**
Fixes #976 .

Summary of changes proposed in this Pull Request:
- turn all `print()` calls in unit tests to `logging.debug()` calls
- silence all `print()` statements in command and other output when `test` is in `sys.argv`

PR checklist:
- [N/A] Updated relevant documentation
- [X] Updated CHANGELOG.md 
- [N/A] Added tests for my change

### CODE REVIEW

**Comment by adamalton** [comment]
This looks good.  But what is baseline.out?  Looks like it's been added by mistake?

**Comment by seawolf42** [comment]
Yup, added by mistake. Removed from the history and latest changes from master are merged, ready to be looked at again when you have a chance, @adamalton. Thanks!

**Comment by adamalton** [comment]
Great, thanks @seawolf42.  One minor thing, which is quite pedantic but would be nice to do, is to change the repeated occurrences of

```python
if not IN_TESTING:
   print (...)
```

with a method on the class.  I.e.:

```python
class DjangaeMigration(object):

    def print(self, value):
        if IN_TESTING:
            print(value)
```

and then use `self.print(...)` in place of `print(...)`.  It would just reduce the repetition, would allow us to easily change the logic of how/whether we print things, and would also allow subclasses to use the same logic.

Sorry, I should have mentioned this the first time! 😬

**Comment by seawolf42** [comment]
That's a great idea, and I'm a little embarrassed I didn't think of it when I was writing this, I was cringing at the code smell but it didn't occur to me to do it that way. I will submit an updated PR in a few minutes.

**Comment by adamalton** [comment]
Nice.  Thanks!

**Pull request merged**
