### PR TITLE
Removing one of the 2 `runtests.sh` scripts.

### PR DESCRIPTION
**Pull request by adamalton**
* Putting all of the functionality into the one in the main directory.
* Removing the unnecessary virtualenv stuff.
* Updating the README accordingly.

### CODE REVIEW

**Comment by Kazade** [comment]
asdlfkjasdklfj?

**Comment by adamalton** [comment]
Ah, tits.

**Comment by olasitarska** [comment]
Nice, this is pretty cool.

**Comment by olasitarska** [comment]
@adamalton oh, I missed one thing. It'd be good to update the same docs [here](https://djangae.readthedocs.org/en/latest/contributing/), or even reference from readme on github. Wanna do that?

**Pull request merged**
