### PR TITLE
Allow the Mapreduce status UI to function when a CSP is enforced with django-csp.

### PR DESCRIPTION
**Pull request by sleepyjames**

### CODE REVIEW

**Comment by adamalton** [comment]
Discussed this, and decided that @sleepyjames will see if we can use the hash method for allowing these specific scripts, rather than just allowing anything on these pages, assuming that's not too much of a pain to do.

**Comment by olasitarska** [comment]
@sleepyjames any updates here?

**Comment by sleepyjames** [comment]
Hey. Sorry the project I was using this on got paused. So I tried the hash approach but it doesn't work for me as the inline JS changes. I think the only way will be to apply the unsafe-inline policy to only the views that require it.

**Comment by olasitarska** [comment]
Let's go with this for now! Thanks @sleepyjames :)

**Pull request merged**
