### PR TITLE
Using gcloud

### LINKED ISSUE #966: Need to update documentation
We need to update documentation https://djangae.readthedocs.io/en/latest/installation/#installation 
for gcloud SDK 

**Need to remove**
app.yaml: 
* application:
* version: 

as this is not required.

**Need to add**
Deployment command:
gcloud app deploy --project [GCLOUD_PROJECT_NAME]  ./

### PR DESCRIPTION
**Pull request by seawolf42**
Fixes #966.

Summary of changes proposed in this Pull Request:
- Updated documentation to explain how to run using `gcloud app deploy`.
- Added ToDos in the `app.yaml` files for `testapp` and `testprodapp` to remind of need to convert these projects to use `gcloud app deploy` instead of `appcfg.py`.

PR checklist:
- [x] Updated relevant documentation
- [x] Updated CHANGELOG.md 
- [N/A] Added tests for my change

### CODE REVIEW

**Comment by seawolf42** [comment]
I would be happy to resolve the ToDo items in the `app.yaml` files for the test projects, but I'll need help ensuring I understand them well enough to confirm I haven't broken anything. Let me know if you want that included in this PR or if it should be deferred to a later date.

**Comment by Kazade** [comment]
This is cool and useful, the only thing is I *know* that some stuff breaks if there's no application in app.yaml (I actually hit this yesterday). 

Before I merge this I'm going to do some testing to try to figure out where we depend on the application from app.yaml and fix it.

**Comment by seawolf42** [comment]
Cool. Happy to work with you to resolve any issues with those apps... point out the issues and I'll update the PR with fixes where I can 😄

**Comment by rspier** [comment]
Issue #1008 is one of those things that breaks when there's no app id in app.yaml

**Comment by seawolf42** [comment]
I'll take a look and see what I can figure out.

**Comment by rspier** [comment]
A simple workaround for things that break under manage.py is to just default app_id to something that's not None.

https://github.com/potatolondon/djangae/blob/master/djangae/core/management/__init__.py#L27

```python
djangae_parser.add_argument('--app_id',` default=None, help='GAE APPLICATION ID')
```

Or in your app's manage.py:

```python
sys.argv.insert(1, "--app_id=something")
```

(that could also be used to set different app_id's for local serving and running test cases to the test cases don't clobber the local serving)

**Comment by seawolf42** [comment]
Does #1019 completely fix the issue you mention above?

**Comment by rspier** [comment]
#1019 is an unrelated issue. 

The default app_id workaround fixes #1008.

**Comment by seawolf42** [comment]
Have you tried using a new SDK version? I can't repro that issue using 1.9.24 of the App Engine SDK with 170.0.0 of the overall SDK.

**Comment by rspier** [comment]
Which issue?  How are you testing it?

**Pull request closed without merging**
