### PR TITLE
tests: update SDK to 1.9.26, docs: update versions

### PR DESCRIPTION
**Pull request by jscissr**
- Update AppEngine SDK to currently newest
- Update django versions in docs (shifting everything by 1)
- Add simplejson to requirements.txt (this was missing when I tried to run the tests the first time)

### CODE REVIEW

**Comment by adamalton** [comment]
Thanks Jan.

What is `simplejson` used by?  It should be susperseded by the standard `json` library, no?

**Comment by jscissr** [comment]
This was the console output before I installed simplejson:

```
C:\Users\Jan\Documents\GitHub\djangae\testapp>python manage.py test
WARNING  2015-09-21 21:43:19,920 simple_search_stub.py:1126] Could not read search indexes from C:\Users\Jan\D
ocuments\GitHub\djangae\testapp\.storage\search_indexes
INFO     2015-09-21 21:43:19,976 blobstore_service.py:70] Starting blobstore service on localhost:8080
WARNING  2015-09-21 21:43:21,532 __init__.py:46] Could not load Pipeline API. Will fix path for testing. Impor
tError: No module named simplejson
WARNING  2015-09-21 21:43:21,552 __init__.py:46] Could not load Pipeline API. Will fix path for testing. Impor
tError: No module named simplejson
WARNING  2015-09-21 21:43:21,609 __init__.py:46] Could not load Pipeline API. Will fix path for testing. Impor
tError: No module named simplejson
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Jan\Documents\GitHub\djangae\djangae\core\management\__init__.py", line 56, in execute_from_c
ommand_line
    return _execute_from_command_line(namespace.sandbox, ['manage.py'] + namespace.args, **overrides)
  File "C:\Users\Jan\Documents\GitHub\djangae\djangae\core\management\__init__.py", line 36, in _execute_from_
command_line
    return django_management.execute_from_command_line(argv)
  File "C:\Users\Jan\Documents\GitHub\djangae\testapp\libs\django\core\management\__init__.py", line 385, in e
xecute_from_command_line
    utility.execute()
  File "C:\Users\Jan\Documents\GitHub\djangae\testapp\libs\django\core\management\__init__.py", line 354, in e
xecute
    django.setup()
  File "C:\Users\Jan\Documents\GitHub\djangae\testapp\libs\django\__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Jan\Documents\GitHub\djangae\testapp\libs\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "C:\Users\Jan\Documents\GitHub\djangae\testapp\libs\django\apps\config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Program Files\Python 2.7.10\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Users\Jan\Documents\GitHub\djangae\djangae\contrib\uniquetool\models.py", line 14, in <module>
    from djangae.contrib.mappers.pipes import MapReduceTask, DjangaeMapperPipeline, PIPELINE_BASE_PATH
  File "C:\Users\Jan\Documents\GitHub\djangae\djangae\contrib\mappers\pipes.py", line 1, in <module>
    from mapreduce.mapper_pipeline import MapperPipeline
  File "C:\Users\Jan\Documents\GitHub\djangae\testapp\libs\mapreduce\mapper_pipeline.py", line 28, in <module>

    from mapreduce import pipeline_base
  File "C:\Users\Jan\Documents\GitHub\djangae\testapp\libs\mapreduce\pipeline_base.py", line 5, in <module>
    import pipeline
  File "C:\Users\Jan\Documents\GitHub\djangae\testapp\libs\pipeline\__init__.py", line 49, in <module>
    from pipeline import *
  File "C:\Users\Jan\Documents\GitHub\djangae\testapp\libs\pipeline\pipeline.py", line 50, in <module>
    import models
  File "C:\Users\Jan\Documents\GitHub\djangae\testapp\libs\pipeline\models.py", line 23, in <module>
    import simplejson
ImportError: No module named simplejson
```

**Comment by jscissr** [comment]
It looks like I should update the versions in `requirements.txt` too, as it's fixed in [master](https://github.com/GoogleCloudPlatform/appengine-pipelines/blob/master/python/src/pipeline/models.py#L23).

**Comment by adamalton** [comment]
Ah, ok, cool.

In [djangae-scaffold](https://github.com/potatolondon/djangae-scaffold/blob/master/requirements.txt) we use our own fork of Pipeline, but I think some of our fixes have now been incorporated into Google's version, the removal of the need for simplejson at least.

**Comment by adamalton** [comment]
Thanks!

**Pull request merged**
